### ISSUE TITLE
Diet affects actions other than eating

### ISSUE THREAD

**Issue by Sylveadiff** [EdwinMindcraft/origins-architectury#19]
When playing a carnivorous origin, right click actions involving edible plant items (such as putting bread into a composter or item frame) have no effect. Given that agriculture is still useful to arachnid players I assume that this is a bug rather than a feature.

**Comment by EdwinMindcraft** [comment]
This should be fixed in 0.7.1.3.
If you are on <=0.7.1.2 try updating to the latest version.

**Comment by Sylveadiff** [comment]
I am using singleplayer and still experiencing this issue while playing on a new save with an arachnid and with disableFoodRestrictions set to true in 0.7.1.4 . Interestingly, it was working for a few in-game days before the issue returned, and while I can now feed pigs I cannot use a composter with food items again. I am now additionally unable to consume rotten flesh.

**Comment by EdwinMindcraft** [comment]
That's because I derped while making disableFoodRestrictions.

**Comment by EdwinMindcraft** [comment]
Also, please do not use disableFoodRestrictions if you aren't using a mod similar to Diet / Spice of Life, it is intended mostly as a patch for those mods.
